name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    env:
      COOP_EMAIL: ${{ secrets.COOP_EMAIL }}
      COOP_PASSWORD: ${{ secrets.COOP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./playwright
        run: npm install
      
      - name: Install Playwright browsers
        working-directory: ./playwright
        run: npx playwright install

      - name: Run Playwright tests
        working-directory: ./playwright
        run: npm run test --env coopEmail=$COOP_EMAIL,coopPassword=$COOP_PASSWORD

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright/playwright-report